# permissions for end users to view oauthproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauthproxy-viewer-role
rules:
- apiGroups:
  - oauth.emdinix.io
  resources:
  - oauthproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oauth.emdinix.io
  resources:
  - oauthproxies/status
  verbs:
  - get
