# permissions for end users to edit oauthproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauthproxy-editor-role
rules:
- apiGroups:
  - oauth.emdinix.io
  resources:
  - oauthproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oauth.emdinix.io
  resources:
  - oauthproxies/status
  verbs:
  - get
